export const GET_PRODUCTS_INIT = 'GET_PRODUCTS_INIT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_FILTER = 'ADD_FILTER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY_TO_CART = 'INCREASE_QUANTITY_TO_CART';
export const DECREASE_QUANTITY_TO_CART = 'DECREASE_QUANTITY_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGOUT = 'SET_LOGOUT';

export const SET_CITY = 'SET_CITY';

export const SET_SORT = 'SET_SORT';
